### ISSUE TITLE
bash wrapping for long lines is not supported 

### ISSUE THREAD

**Issue by kvmw** [ReactiveCircus/android-emulator-runner#100]
Following syntax is not supported. 
```
script: |
  ./gradlew  connectedAndroidTest \
  -Pp1=foo \
  -Pp2=bar \
  -Pp3=baz
```
It's handy, specially when one has many params to pass to build.

**Comment by hostilefork** [comment]
Backslash support is important when you have multiple commands (where at least some of them are long).

The slowness of starting up and shutting down the emulator means that if you have a lot of commands, you will likely want to be running them all as one script--if possible!

However, in the case of merely running one command...you might consider using YAML's **`>`** operator.

    Key: >
      this is my very very very
      long string

This produces `this is my very very very long string\n`.  If you don't want the newline at the end, then use `>-` instead of `>`.

More details on this and other operators: https://stackoverflow.com/a/21699210

---

Brainstorm: As a potential alternative to `script:` that takes one long script, there could be `commands:` ?  Then on a given command you could use the `>` trick and not need backslashes:

    commands:
    - some short command
    - >
       some long
       command here

But I'm not sure that's an improvement.  And backslashes are a fairly entrenched shell continuation method.
