### ISSUE TITLE
Ram Size Option follow up 

### ISSUE THREAD

**Issue by JPrendy** [ReactiveCircus/android-emulator-runner#139]
Hi there,

I noticed some improvements in my builds since the merging of this pr [Add option to modify the number of cores](https://github.com/ReactiveCircus/android-emulator-runner/pull/130).

Just wondering the same author created a pr [Add ram size option](https://github.com/ReactiveCircus/android-emulator-runner/pull/128) but closed it. Is that something you can look into for this action. I am not sure if the author found any negatives when working on the feature, but it looks like an interesting feature to add to the runner.

**Comment by ychescale9** [comment]
CC @AfzalivE

**Comment by AfzalivE** [comment]
Sure I'll push it later today or this weekend. I added a lot of options so I wasn't sure which ones you'd like.

@ychescale9 

Would you like these in addition to the ram size option?

- disable-spellchecker
- disable-autofill
- longpress-timeout
- enable-hw-keyboard
- enable-logcat (reads and saves the logcat to `artifacts/logcat.log`)
- print-config-ini (this one is probably not so useful)
- vm-heap-size (this one was pretty useless since the `system_server` VM heap was unaffected by changing this :( )

**Comment by ychescale9** [comment]
Thanks @AfzalivE ! Let's add the following for now :)
- `ram-size`
- `disable-spellchecker`
- `longpress-timeout`
- `enable-hw-keyboard`

**Comment by andreRBarata** [comment]
Hi there,

I was wondering if this update was being looked at at the moment or if its in the back burner?

Expecially the ram-size one

**Comment by ychescale9** [comment]
I can take a look this weekend, unless @AfzalivE wants to continue his work here?

**Comment by AfzalivE** [comment]
Really sorry that I've been missing from this project for a while and I'm not going to be home this weekend :(

The Doist fork should have everything you need though.

**Comment by ychescale9** [comment]
`ram-size` is now available.
