### ISSUE TITLE
Support Linux machines

### ISSUE THREAD

**Issue by nuhkoca** [ReactiveCircus/android-emulator-runner#15]
Hello,

As Github charges us 10 times per run on macOS machines, is there any way to support this action for Linux machines, too? Thanks.

**Comment by ychescale9** [comment]
Hi. Unfortunately we can't support Linux due to the Linux VMs not supporting KVM, which is required for running hardware accelerated Emulators.

The host VMs not supporting KVM is still the main hurdle for running hardware-accelerated Android Emulators on cloud hosted CI. The macOS VMs happen to have HAXM installed hence I created this Action to take advantage of the hardware acceleration support.

As an alternative you could look at [Cirrus CI](https://cirrus-ci.org/) which provides KVM-enabled Linux VMs and pricing seems pretty reasonable. Here are some [templates](https://github.com/ReactiveCircus/cirrusci-android-templates) to help you get started.

**Comment by nuhkoca** [comment]
@ychescale9 thanks for a prompt reply. I will take a look then :)

**Comment by PaulWoitaschek** [comment]
And can you make the error a warning? I have a small testcase and like to run it without hardware acceleration anyways.

**Comment by ychescale9** [comment]
We could, but then I don't think you'll get much by using this action as you could just use one of the docker images with ARM system images and run it on a `ubuntu-xxx` VM without a custom action.

If we were to support running on linux VM with old system images we'll need to support specifying `armeabi-v7a ` or `arm64-v8a` for `arch`. I haven't tried but I remember these images are only available in _some_  of the older API levels and it's just hit or miss.

I'm also tracking [this issue](https://github.com/ReactiveCircus/android-emulator-runner/issues/29) for supporting custom system images and I wonder if we'll need to lift this macOS-only restriction after all.

**Comment by PaulWoitaschek** [comment]
Will it would be more robust and I would not need to perform additional platform checks but get the acceleration when available.

**Comment by PaulWoitaschek** [comment]
I don't fully understand the implications but would this solve the whole problem in general?
https://android-developers.googleblog.com/2020/03/run-arm-apps-on-android-emulator.html

**Comment by ychescale9** [comment]
What it means is that if your app depends on native libraries that only runs on ARM-based system images, now you can run it on the modern x86 / x86_64 images.

Unfortunately this doesn't help us as the limitation of not enabling native hardware acceleration on the Linux VMs comes from the CI providers (GitHub Actions, CircleCI, travis etc) and [Cirrus CI](https://cirrus-ci.org/) is the only one I know that doesn't have this restriction.

This article should give you more context: [Running Android Instrumented Tests on CI](https://dev.to/ychescale9/running-android-emulators-on-ci-from-bitrise-io-to-github-actions-3j76).

**Comment by ychescale9** [comment]
Linux (no hardware acceleration) supported is now available!

**Comment by nuhkoca** [comment]
That's a great news, thanks for your effort!

**Comment by PaulWoitaschek** [comment]
Muchas Gracias!
