### ISSUE TITLE
insturmenation test are failing randomly with mockserver

### ISSUE THREAD

**Issue by TheReprator** [ReactiveCircus/android-emulator-runner#162]
Hi Mate,

My test are failing randomly

Workflow Success:
	https://github.com/TheReprator/Wipro/runs/2911975969?check_suite_focus=true
	
Workflow Fail:
	https://github.com/TheReprator/Wipro/runs/2911975942?check_suite_focus=true

Exception logs:
   `reprator.wipro.factlist.test.FactListKaspressoTest > load_item_successfully_in_recyclerview_with_error_on_pullToRefresh[test(AVD) - 6.0] FAILED 
	androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (an instance of com.google.android.material.snackbar.Snackbar$SnackbarLayout)
	

reprator.wipro.factlist.test.FactListKaspressoTest > loadErrorViewOnLaunch_withSuccessfulReload[test(AVD) - 6.0] FAILED 
	junit.framework.AssertionFailedError: 'is displayed on the screen to the user' doesn't match the selected view.
	Expected: is displayed on the screen to the user

> Task :appModules:factList:connectedDebugAndroidTest FAILED`

Repo:  https://github.com/TheReprator/Wipro
Branch: codeCoverage
workflow: push.yml

Looking forward for a solution.

Regards,
Vikram Singh

**Comment by ashutoshgngwr** [comment]
Flaky behaviour is rather common for complex UI tests running on Android Emulators, especially in CI environments. You should use a retry mechanism, e.g. a [RetryTestRule](https://github.com/ashutoshgngwr/noice/blob/master/app/src/androidTest/java/com/github/ashutoshgngwr/noice/RetryTestRule.kt) that retries a failing test for a fixed number of times. Additionally, you can also use a [waitForView](https://github.com/ashutoshgngwr/noice/blob/03c5ec85968dc768081bba32ae1028a3134f98ab/app/src/androidTest/java/com/github/ashutoshgngwr/noice/EspressoX.kt#L98-L146) instead of `onView(...).check(matches(...))`. `onView().check(matches(..))` will find the view and check assertions. It fails immediately if the view state is not as expected. `waitForView` combines both steps and waits for a view that matches the assertions, e.g.

```java
onView(withId(R.id.test)).check(matches(isDisplayed()))
// becomes
waitForView(withId(R.id.test), isDisplayed())
```
