### ISSUE TITLE
Job times out due to package id being in inconsistent location

### ISSUE THREAD

**Issue by XiangRongLin** [ReactiveCircus/android-emulator-runner#168]
My CI job was cancelled after 6h because the android emulator runner action got stuck

Logs
https://github.com/TeamNewPipe/NewPipe/pull/6673/checks?check_run_id=3080440435

[logs.zip](https://github.com/ReactiveCircus/android-emulator-runner/files/6834395/logs.zip)

```log
 /usr/bin/unzip -o -q emulator.zip -d /Users/runner/Library/Android/sdk
Installing system images.
/bin/sh -c \sdkmanager --install 'system-images;android-29;default;x86' > /dev/null
Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
Error: The operation was canceled.
```

I'm running the action on API level 21 and 29, the 21 one succeeds, the 29 one fails. [workflow](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/workflows/ci.yml#L70).  

Because of this i don't know what the problem is

**Comment by bsalesc** [comment]
I have the same issue with 28 API level and was working in the last build 21 hours ago.

**Comment by JohnBellSageCom** [comment]
Saw the same issue a couple of days ago, then changed the config which resolved the issue for 24 hours. The issue is now back again.

**Comment by bsalesc** [comment]
Changing from 28 to 27 worked.

**Comment by marcuspridham** [comment]
Ran into this also. First tried changing emulator-build but that didn't help.

Changing the target to google_apis worked though.
```
        with:
          api-level: 28
          target: google_apis
```

**Comment by mrsarm** [comment]
I think the problem is that the **sdkmanager is hanging the script because waits the user to accept the SDK license terms**.

How I get to that conclusion? I just tried to execute the last command before the job get frozen, and the command does nothing other than wait for nothing like in my Github Action job:

```
$ sdkmanager --install 'system-images;android-29;default;x86' > /dev/null

```

But if you remove the ` > /dev/null` suffix, it clears what happens:

```
$ sdkmanager --install 'system-images;android-29;default;x86'
License android-sdk-preview-license:    ] 10% Computing updates...              
---------------------------------------
To get started with the Android SDK Preview, you must agree to the following terms and conditions. As described below, please note that this is a preview version of the Android SDK, subject to change, that you use at your own risk. The Android SDK Preview is not a stable release, and may contain errors and defects that can result in serious damage to your computer systems, devices and data.

This is the Android SDK Preview License Agreement (the "License Agreement").

1. Introduction

1.1 The Android SDK Previ ...
...
..................... LONG LICENSE TEMS .....................
...

June 2014.
---------------------------------------
Accept? (y/N):
```

Unfortunately there is no option to auto-accept terms of conditions, what I saw in other [posts](https://stackoverflow.com/questions/38096225/automatically-accept-all-sdk-licences) with similar issues trying to run the sdkmanager in CI enviroments is to execute it piped with the `yes` command:

```
$ yes | sdkmanager --install 'system-images;android-29;default;x86' > /dev/null
```

**Comment by mrsarm** [comment]
Confirmed that what I mention is the problem, because using the [workaround](#issuecomment-881513656) mentioned by @marcuspridham of setting `target: google_apis` works, and looking at the CLI, what is executed is:

```
sdkmanager --install 'system-images;android-30;google_apis;x86' > /dev/null
```

And executing the same in my local computer, sdkmager does not ask me to confirm any license agreement.

I have created the PR https://github.com/ReactiveCircus/android-emulator-runner/pull/170 with the patch.

**Comment by ashutoshgngwr** [comment]
Thanks, @marcuspridham and @ychescale9 for resolving it in a timely manner. When can we expect it to be released?

**Comment by ychescale9** [comment]
Will try to do a release in a few hours

**Comment by ychescale9** [comment]
This has been released. Thanks again @marcuspridham for the fix!
